---
title: "Clustering Exercises"
author: "Levi Waldron"
date: "March 17, 2016"
output: html_document
---

# Question 1

```{r}
set.seed(1)
m = 10000
n = 24
x = matrix(rnorm(m*n),m,n)
colnames(x)=1:n
```

Calculate distance:
```{r}
d <- dist(t(x))
```

Clustering:
```{r}
hc <- hclust(d)
```

Plot dendrogram:

```{r}
plot(as.dendrogram(hc))
```


# Question 2

```{r}
ct <- cutree(hc, h=143)
length(unique(ct))
max(ct)
```

# Question 4

If needed to install GSE5859Subset, either use devtools:

```{r, eval=FALSE}
devtools::install_git("genomicsclass/GSE5859Subset")
```

Or using biocLite():
```{r}
BiocInstaller::biocLite("genomicsclass/GSE5859Subset")
```

```{r}
library(GSE5859Subset)
data(GSE5859Subset)
set.seed(10)
km <- kmeans(t(geneExpression), centers=5)
table(kmeans = km$cluster, date = sampleInfo$date)
```

Pick 25 genes with highest MAD:

```{r}
mads <- matrixStats::rowMads(geneExpression)
gene25 <- geneExpression[rank(-mads) <= 25, ]
annot25 <- geneAnnotation[rank(-mads) <= 25, ]
```

```{r, message=FALSE}
library(gplots)
heatmap.2(gene25, scale="row", 
          labRow = annot25$CHR, 
          labCol = sampleInfo$date,
          ColSideColors = c("black", "lightgrey")[sampleInfo$group+1], 
          trace = "none")
```


