---
title: "getting_started"
author: "lcleo"
date: "16 February 2016"
output: html_document
---

###exercises getting started

```{r}
library(downloader) 
url <- "https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/femaleMiceWeights.csv"
filename <- "femaleMiceWeights.csv" 
download(url, destfile=filename)
```

```{r}
#1 Read the file
data <- read.csv('femaleMiceWeights.csv')
 
### There are several different ways to have a first look to the data
summary(data) 
head(data)
View(data)
dim(data)
class(data)
class(data[[1]])  #the .csv converts by default characters to factors 
class(data[[2]])


#2 Report the body weight of the mouse in the exact column
weights <- data$Bodyweight
weights
class(weights) #it returns a numeric vector with all body weights

#3 Extract the 12th row and second column
data[12,1] #chow Levels: chow hf 

#4 how many mice are included in our dataset?
len <-length (data$Diet)
len

#5 what rows are associated with hf, compute average weight of these mice
hfmice <- data[,1] == 'hf' #it gives me TRUE from 13 to 24
mean_hfmice <- mean (data[13:24, 2]) #OR
mean_hfmice <- mean (data[data[,1] == 'hf',2])  
mean_hfmice

#6 take a random sample of size 1 from numbers 13 to 24, weight of mouse represented by this row
set.seed(1) #you use it exaclty before you use the random number generator
x <- 13:24
sample(x, 1) #It gives me number 16
data[16,2]  # The weight is 25.34
#ORR
data[sample(13:24, size=1), 2]
```



