---
title: "Anscombe"
author: "Calogero Zarbo"
date: "March 17, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load files anscombe[1-4].csv:

```{r}
library(readr)
ds1 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe1.csv")
ds2 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe2.csv")
ds3 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe3.csv")
ds4 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe4.csv")
```

# Perform numeric summaries
```{r}
summary(anscombe1)
summary(anscombe2)
summary(anscombe3)
summary(anscombe4)
```

# Do linear regressions
```{r}
m1 <- lm(y1 ~ x1, data=anscombe1)
m2 <- lm(y2 ~ x2, data=anscombe2)
m3 <- lm(y3 ~ x3, data=anscombe3)
m4 <- lm(y4 ~ x4, data=anscombe4)
```

# Then, do graphical exploration
```{r}[echo=FALSE]
plot(anscombe1)
abline(m1)

plot(anscombe2)
abline(m2)

plot(anscombe3)
abline(m3)

plot(anscombe4)
abline(m4)
```