---
title: "anscombe"
author: "Serena"
date: "04 marzo 2016"
output: html_document
---

```{r}
library(Biobase)
library(readr)
anscombe1 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe1.csv")
anscombe2 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe2.csv")
anscombe3 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe3.csv")
anscombe4 <- readr::read_csv("https://raw.githubusercontent.com/waldronlab/AppStatTrento/master/Session4/anscombe4.csv")
```

##Perform numeric summaries

```{r}
summary(anscombe1)
summary(anscombe2)
summary(anscombe3)
summary(anscombe4)
```

##Perform linea regressions
```{r}
mod1 <- lm(y1 ~ x1, data=anscombe1[,2-3])
mod2 <- lm(y2 ~ x2, data=anscombe2[,2-3])
mod3 <- lm(y3 ~ x3, data=anscombe3[,2-3])
mod4 <- lm(y4 ~ x4, data=anscombe4[,2-3])
```

##Do graphical explorations
```{r}
plot(anscombe1[,2-3])
abline(mod1)

plot(anscombe2[,2-3])
abline(mod2)

plot(anscombe3[,2-3])
abline(mod3)

plot(anscombe4[,2-3])
abline(mod4)
```